# Generated by Django 5.2.2 on 2025-06-11 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=50, unique=True, verbose_name='員工編號')),
                ('staff_name', models.CharField(max_length=100, verbose_name='員工姓名')),
                ('employment_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='受聘形式')),
                ('employment_type_remark', models.TextField(blank=True, null=True, verbose_name='受聘形式備註')),
                ('dsej_registration_status', models.CharField(blank=True, max_length=50, null=True, verbose_name='教青局登記資料')),
                ('dsej_registration_rank', models.CharField(blank=True, max_length=100, null=True, verbose_name='教青局登記職級')),
                ('entry_date', models.DateField(blank=True, null=True, verbose_name='入職日期')),
                ('departure_date', models.DateField(blank=True, null=True, verbose_name='離職日期')),
                ('retirement_date', models.DateField(blank=True, null=True, verbose_name='退休日期')),
                ('position_grade', models.CharField(blank=True, max_length=100, null=True, verbose_name='職稱/任教年級')),
                ('teaching_staff_salary_grade', models.CharField(blank=True, max_length=50, null=True, verbose_name='教學人員薪級')),
                ('basic_salary_points', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='薪級基本點數')),
                ('adjusted_salary_points', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='調整增薪點數')),
                ('provident_fund_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='公積金類別')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='備註')),
                ('name_chinese', models.CharField(max_length=100, verbose_name='員工姓名(中文)')),
                ('name_foreign', models.CharField(blank=True, max_length=150, null=True, verbose_name='員工姓名(外文)')),
                ('gender', models.CharField(blank=True, max_length=10, null=True, verbose_name='性別M/F')),
                ('marital_status', models.CharField(blank=True, max_length=20, null=True, verbose_name='婚姻狀況')),
                ('birth_place', models.CharField(blank=True, max_length=100, null=True, verbose_name='出生地點')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='出生日期')),
                ('origin', models.CharField(blank=True, max_length=100, null=True, verbose_name='籍貫')),
                ('id_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='證件類別')),
                ('id_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='證件號碼')),
                ('id_expiry_date', models.DateField(blank=True, null=True, verbose_name='證件有效期')),
                ('bank_account_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='大豐銀行澳門幣戶口賬號')),
                ('social_security_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='社保號碼')),
                ('home_phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='住宅電話')),
                ('mobile_phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='手提電話')),
                ('address', models.TextField(blank=True, null=True, verbose_name='住址')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='電郵')),
                ('alumni_class', models.CharField(blank=True, max_length=50, null=True, verbose_name='級社(校友適用)')),
                ('alumni_class_year', models.CharField(blank=True, max_length=10, null=True, verbose_name='級社_年級(校友適用)')),
                ('alumni_class_duration', models.CharField(blank=True, max_length=20, null=True, verbose_name='級社_年數(校友適用)')),
                ('teacher_certificate_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='教師證號碼')),
                ('teaching_staff_rank', models.CharField(blank=True, max_length=100, null=True, verbose_name='教學人員職級')),
                ('teaching_staff_rank_effective_date', models.DateField(blank=True, null=True, verbose_name='教學人員職級生效日期')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='緊急聯絡人姓名')),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='緊急聯絡人電話')),
                ('emergency_contact_relationship', models.CharField(blank=True, max_length=50, null=True, verbose_name='與緊急聯絡人之關係')),
                ('user_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='管理員')),
            ],
            options={
                'verbose_name': '教職員基本資料',
                'verbose_name_plural': '教職員基本資料',
            },
        ),
        migrations.CreateModel(
            name='ProfessionalQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification_name', models.CharField(max_length=150, verbose_name='專業資格名稱')),
                ('issuing_organization', models.CharField(max_length=150, verbose_name='頒發機構')),
                ('issue_date', models.DateField(verbose_name='頒授日期')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professional_qualifications', to='staff_management.staffprofile', verbose_name='教職員')),
            ],
            options={
                'verbose_name': '專業資格',
                'verbose_name_plural': '專業資格',
            },
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('relationship', models.CharField(max_length=50, verbose_name='關係')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='出生日期')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='年齡')),
                ('education_level', models.CharField(blank=True, max_length=100, null=True, verbose_name='學歷程度')),
                ('institution', models.CharField(blank=True, max_length=150, null=True, verbose_name='教育機構/任職機構')),
                ('alumni_class', models.CharField(blank=True, max_length=50, null=True, verbose_name='級社(校友適用)')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to='staff_management.staffprofile', verbose_name='教職員')),
            ],
            options={
                'verbose_name': '家庭成員',
                'verbose_name_plural': '家庭成員',
            },
        ),
        migrations.CreateModel(
            name='EducationBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_period', models.CharField(max_length=50, verbose_name='就讀年份(如:2016-2020)')),
                ('school_name', models.CharField(max_length=150, verbose_name='就讀學校')),
                ('education_level', models.CharField(max_length=100, verbose_name='教育程度')),
                ('degree_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='專科學位名稱')),
                ('certificate_date', models.DateField(blank=True, null=True, verbose_name='獲得證書日期')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_backgrounds', to='staff_management.staffprofile', verbose_name='教職員')),
            ],
            options={
                'verbose_name': '學歷狀況',
                'verbose_name_plural': '學歷狀況',
            },
        ),
        migrations.CreateModel(
            name='AssociationPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('association_name', models.CharField(max_length=150, verbose_name='社團名稱')),
                ('position', models.CharField(max_length=100, verbose_name='職位')),
                ('start_year', models.CharField(max_length=10, verbose_name='開始年期')),
                ('end_year', models.CharField(blank=True, max_length=10, null=True, verbose_name='結束年期')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='association_positions', to='staff_management.staffprofile', verbose_name='教職員')),
            ],
            options={
                'verbose_name': '社團職務',
                'verbose_name_plural': '社團職務',
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employment_period', models.CharField(max_length=50, verbose_name='任職年份(如:2016-2020)')),
                ('organization', models.CharField(max_length=150, verbose_name='任職機構')),
                ('position', models.CharField(max_length=100, verbose_name='任職職位')),
                ('salary', models.CharField(blank=True, max_length=50, null=True, verbose_name='薪金')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experiences', to='staff_management.staffprofile', verbose_name='教職員')),
            ],
            options={
                'verbose_name': '工作經驗',
                'verbose_name_plural': '工作經驗',
            },
        ),
    ]
