# Generated by Django 5.2.2 on 2025-06-11 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workexperience',
            options={'verbose_name': '工作經驗 (校外為主)', 'verbose_name_plural': '工作經驗'},
        ),
        migrations.AddField(
            model_name='educationbackground',
            name='is_phd',
            field=models.BooleanField(default=False, verbose_name='博士學位PhD'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否在職'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='school_seniority',
            field=models.FloatField(blank=True, null=True, verbose_name='在校年資'),
        ),
        migrations.CreateModel(
            name='EmploymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employment_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='受聘形式')),
                ('entry_date', models.DateField(verbose_name='入職日期')),
                ('departure_date', models.DateField(blank=True, null=True, verbose_name='離職日期')),
                ('is_valid_for_seniority', models.BooleanField(default=True, verbose_name='有效年資')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='備註')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employment_records', to='staff_management.staffprofile', verbose_name='教職員')),
            ],
            options={
                'verbose_name': '在職記錄',
                'verbose_name_plural': '在職記錄',
                'ordering': ['-entry_date'],
            },
        ),
    ]
