# Generated by Django 5.2.2 on 2025-06-11 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_management', '0002_alter_workexperience_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffprofile',
            name='school_seniority',
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='school_seniority_description',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='在校年資(描述)'),
        ),
    ]
