# Generated by Django 5.2.2 on 2025-06-12 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_management', '0003_remove_staffprofile_school_seniority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationbackground',
            name='is_foreign_national',
            field=models.BooleanField(default=False, verbose_name='是否外籍人士'),
        ),
        migrations.AddField(
            model_name='educationbackground',
            name='is_overseas_study',
            field=models.BooleanField(default=False, verbose_name='是否留學'),
        ),
    ]
