# Generated by Django 5.2.2 on 2025-06-12 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_management', '0004_educationbackground_is_foreign_national_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationbackground',
            name='is_foreign_national',
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='is_foreign_national',
            field=models.BooleanField(default=False, verbose_name='是否外籍人士'),
        ),
    ]
