# Generated by Django 5.2.2 on 2025-06-12 03:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_management', '0005_remove_educationbackground_is_foreign_national_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='created_by_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_staff_profiles', to=settings.AUTH_USER_MODEL, verbose_name='操作創建的管理員'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='user_account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='關聯用戶賬號(可選)'),
        ),
    ]
