# Generated by Django 5.2.2 on 2025-08-11 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_management', '0006_staffprofile_created_by_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='is_master',
            field=models.BooleanField(default=False, verbose_name='是否碩士學位'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='在職狀態'),
        ),
    ]
