# Generated by Django 5.2.2 on 2025-08-11 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_management', '0007_staffprofile_is_master_alter_staffprofile_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='staff_photos/', verbose_name='員工照片'),
        ),
    ]
