# Generated by Django 5.2.2 on 2025-08-11 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_management', '0008_staffprofile_profile_picture'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', '新增 Create'), ('update', '更新 Update'), ('delete', '刪除 Delete'), ('view', '查看 View'), ('export', '匯出 Export'), ('import', '匯入 Import'), ('login', '登入 Login'), ('logout', '登出 Logout')], max_length=20, verbose_name='操作類型')),
                ('resource_type', models.CharField(max_length=50, verbose_name='資源類型')),
                ('resource_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='資源ID')),
                ('description', models.TextField(verbose_name='操作描述')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='瀏覽器信息')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='操作時間')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作用戶')),
            ],
            options={
                'verbose_name': '系統日誌',
                'verbose_name_plural': '系統日誌',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', '系統管理員 System Admin'), ('hr', '人事管理員 HR Manager'), ('supervisor', '主管 Supervisor'), ('staff', '一般員工 Staff'), ('readonly', '唯讀用戶 Read Only')], max_length=20, verbose_name='角色')),
                ('department', models.CharField(blank=True, max_length=100, null=True, verbose_name='部門')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('is_active', models.BooleanField(default=True, verbose_name='角色狀態')),
                ('can_view_all_staff', models.BooleanField(default=False, verbose_name='可查看所有員工')),
                ('can_edit_staff_data', models.BooleanField(default=False, verbose_name='可編輯員工資料')),
                ('can_export_data', models.BooleanField(default=False, verbose_name='可匯出資料')),
                ('can_import_data', models.BooleanField(default=False, verbose_name='可匯入資料')),
                ('can_manage_users', models.BooleanField(default=False, verbose_name='可管理用戶')),
                ('can_view_statistics', models.BooleanField(default=True, verbose_name='可查看統計')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='關聯用戶')),
            ],
            options={
                'verbose_name': '用戶角色',
                'verbose_name_plural': '用戶角色',
            },
        ),
    ]
