# Generated by Django 5.2.2 on 2025-08-12 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_management', '0009_systemlog_userrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationbackground',
            name='is_master',
            field=models.BooleanField(default=False, verbose_name='碩士學位Master'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='is_overseas_study',
            field=models.BooleanField(default=False, verbose_name='是否留學'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='is_phd',
            field=models.BooleanField(default=False, verbose_name='是否博士學位'),
        ),
    ]
