# Generated by Django 5.2.2 on 2025-11-12 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_management', '0010_add_dual_education_flags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='email',
            field=models.EmailField(default='待更新@pcms.edu.mo', max_length=254, verbose_name='電郵'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='mobile_phone',
            field=models.CharField(default='待更新', max_length=30, verbose_name='手提電話'),
        ),
    ]
