# Generated by Django 5.2.2 on 2025-11-12 04:28

from django.db import migrations

def populate_required_fields(apps, schema_editor):
    """
    安全填充必填字段的空值
    為現有的 NULL 或空值記錄設置合理的默認值
    """
    StaffProfile = apps.get_model('staff_management', 'StaffProfile')
    
    # 更新手機號碼為空或 NULL 的記錄
    StaffProfile.objects.filter(mobile_phone__isnull=True).update(mobile_phone='待更新')
    StaffProfile.objects.filter(mobile_phone='').update(mobile_phone='待更新')
    
    # 更新郵箱為空或 NULL 的記錄
    StaffProfile.objects.filter(email__isnull=True).update(email='待更新@pcms.edu.mo')
    StaffProfile.objects.filter(email='').update(email='待更新@pcms.edu.mo')
    
    # 對於有員工編號的記錄，嘗試創建更具體的默認值
    for staff in StaffProfile.objects.filter(mobile_phone='待更新'):
        if staff.staff_id:
            staff.mobile_phone = f'待更新_{staff.staff_id[-4:]}'  # 使用員工編號末4位
            staff.save(update_fields=['mobile_phone'])
    
    for staff in StaffProfile.objects.filter(email='待更新@pcms.edu.mo'):
        if staff.staff_id:
            staff.email = f'待更新_{staff.staff_id}@pcms.edu.mo'  # 使用員工編號
            staff.save(update_fields=['email'])

def reverse_populate_required_fields(apps, schema_editor):
    """
    回滾操作 - 將默認值改回 NULL（如果字段允許）
    """
    StaffProfile = apps.get_model('staff_management', 'StaffProfile')
    
    # 注意：由於我們要將字段改為必填，這個回滾可能不會完全有效
    # 這裡只是為了遵循最佳實踐
    StaffProfile.objects.filter(mobile_phone__startswith='待更新').update(mobile_phone='')
    StaffProfile.objects.filter(email__startswith='待更新').update(email='')


class Migration(migrations.Migration):

    dependencies = [
        ('staff_management', '0011_add_required_field_defaults'),
    ]

    operations = [
        migrations.RunPython(
            populate_required_fields,
            reverse_populate_required_fields,
            atomic=True,
        ),
    ]
