# Generated by Django 5.2.2 on 2025-11-12 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_management', '0012_populate_required_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='電郵 Email'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='緊急聯絡人姓名 Emergency Contact Name'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='緊急聯絡人電話 Emergency Contact Phone'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='emergency_contact_relationship',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='與緊急聯絡人之關係 Emergency Contact Relationship'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='mobile_phone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='手提電話 Mobile Phone'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='name_chinese',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='員工姓名(中文) Staff Name (Chinese)'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='name_foreign',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='員工姓名(外文) Staff Name (Foreign)'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='staff_id',
            field=models.CharField(max_length=50, unique=True, verbose_name='員工編號 Staff ID'),
        ),
    ]
