# Generated by Django 5.2.2 on 2025-12-08 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_management', '0013_alter_staffprofile_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='contract_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='合約編號'),
        ),
    ]
