"""
Django settings for pcms_staff project.

Generated by 'django-admin startproject' using Django 5.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-!pne1rg+f1_we^jyc0-_ask*9uoh6t5ok8e+k&vaq)xfl_*kf+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ALLOWED_HOSTS 設定 - 支援指定網域段
ALLOWED_HOSTS = [
    # 本地開發
    'localhost',
    '127.0.0.1', 
    '0.0.0.0',
    # Docker 容器名稱
    'frontend',
    'backend', 
    'pcms_staff_backend',
]+ [f'192.168.12.{i}' for i in range(1, 255)] + [f'172.188.118.{i}' for i in range(1, 255)]



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework.authtoken', # <--- 添加這一行
    'staff_management.apps.StaffManagementConfig', # 新增
    'application_submission.apps.ApplicationSubmissionConfig', # 新增
    'corsheaders',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'pcms_staff.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'templates',  # 添加全局模板目錄
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pcms_staff.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

import os

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'pcms_staff_db',
        'USER': 'pcms_admin',
        'PASSWORD': 'pcms_admin',
        'HOST': 'pcms_staff_mysql',  # Docker容器名稱
        'PORT': '3306',
        'OPTIONS': {
            'charset': 'utf8mb4',
            'sql_mode': 'traditional',
        },
    },
    'sqlite_backup': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# 根據環境變量決定使用哪個數據庫
if os.getenv('DB_ENGINE') == 'sqlite' or os.getenv('USE_SQLITE') == 'true':
    DATABASES['default'] = DATABASES['sqlite_backup']


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'zh-hant' # 修改

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# 媒體文件配置 - 用於處理用戶上傳的文件（如員工照片）
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS 設定 - 允許所有來源（用於開發環境）
CORS_ALLOW_ALL_ORIGINS = True

# 如果是生產環境，可以改用以下設定：
# CORS_ALLOWED_ORIGINS = [
#     "http://localhost:3000",
#     "http://127.0.0.1:3000",
#     "http://localhost:8000",
#     "http://127.0.0.1:8000",
#     "http://172.188.118.206:3000",
#     "http://172.188.118.206:8000",
#     # 其他需要的地址
# ]

# CSRF配置 - 信任整個內網段（包含HTTPS）
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
    "http://localhost:8000", 
    "http://127.0.0.1:3000",
    "http://127.0.0.1:8000",
    "https://localhost",
    "https://localhost:3000",
    "https://localhost:8000",
    "https://127.0.0.1",
    "https://127.0.0.1:3000", 
    "https://127.0.0.1:8000",
    # 172.188.118.* 網段
    "http://172.188.118.*:3000",
    "http://172.188.118.*:8000",
    "https://172.188.118.*",
    "https://172.188.118.*:3000",
    "https://172.188.118.*:8000",
    # 192.168.12.* 網段
    "http://192.168.12.*:3000",
    "http://192.168.12.*:8000",
    "https://192.168.12.*",
    "https://192.168.12.*:3000",
    "https://192.168.12.*:8000",
]

# SSL/HTTPS 安全設定
HTTPS_ENABLED = os.getenv('HTTPS_ENABLED', 'false').lower() == 'true'
if HTTPS_ENABLED:
    # 僅在啟用HTTPS時應用這些設定
    SECURE_SSL_REDIRECT = os.getenv('SECURE_SSL_REDIRECT', 'false').lower() == 'true'
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True

# Logging Configuration
LOGGING_DIR = BASE_DIR / 'logs'
if not LOGGING_DIR.exists():
    LOGGING_DIR.mkdir(parents=True, exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'file_info': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGGING_DIR / 'django_info.log',
            'maxBytes': 1024 * 1024 * 5,  # 5 MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
        'file_error': {
            'level': 'ERROR',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGGING_DIR / 'django_error.log',
            'maxBytes': 1024 * 1024 * 5,  # 5 MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file_info', 'file_error'],
            'level': 'INFO',
            'propagate': True,
        },
        'django.request': {
            'handlers': ['file_error'], # Django的请求错误会记录到error log
            'level': 'ERROR',
            'propagate': False,
        },
        # 您可以為您的應用程式定義特定的 logger
        'staff_management': { # 假設您的 app 名稱是 staff_management
            'handlers': ['console', 'file_info', 'file_error'],
            'level': 'INFO',
            'propagate': False,
        },
        'application_submission': { # 假設您的 app 名稱是 application_submission
            'handlers': ['console', 'file_info', 'file_error'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}


# 日誌文件夾路徑
LOGS_DIR = BASE_DIR / 'logs'
if not os.path.exists(LOGS_DIR):
    os.makedirs(LOGS_DIR)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'info_file': {
            'level': 'INFO',
            'class': 'logging.handlers.TimedRotatingFileHandler', # 使用時間輪替
            'filename': LOGS_DIR / 'django_info.log',
            'when': 'midnight',  # 每天午夜輪替
            'interval': 1,       # 每天一次
            'backupCount': 7,    # 保留7個備份文件 (即7天)
            'formatter': 'verbose',
            'encoding': 'utf-8', # 確保中文等字符正確記錄
        },
        'error_file': {
            'level': 'ERROR',
            'class': 'logging.handlers.TimedRotatingFileHandler', # 使用時間輪替
            'filename': LOGS_DIR / 'django_error.log',
            'when': 'midnight',  # 每天午夜輪替
            'interval': 1,       # 每天一次
            'backupCount': 7,    # 保留7個備份文件 (即7天)
            'formatter': 'verbose',
            'encoding': 'utf-8',
        },
        'frontend_log_file': { # 新增一個 handler 專門給前端日誌，如果想分開文件
            'level': 'DEBUG', # 記錄所有從前端發來的級別
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': LOGS_DIR / 'frontend_events.log', # 可以是獨立文件
            'when': 'midnight',
            'interval': 1,
            'backupCount': 7,
            'formatter': 'simple', # 或者 'verbose'
            'encoding': 'utf-8',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'info_file', 'error_file'],
            'level': 'INFO', # Django 框架本身的日誌級別
            'propagate': True,
        },
        # 您可以為特定的 app 定義 logger，例如：
        'staff_management': { # 假設您的 app 名為 staff_management
            'handlers': ['console', 'info_file', 'error_file', 'frontend_log_file'],
            'level': 'DEBUG', # app 級別的日誌可以更詳細
            'propagate': False, # 不再傳遞給 root logger，避免重複記錄
        },
        'application_submission': { # 為 application_submission app 添加 logger
            'handlers': ['console', 'info_file', 'error_file'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
    'root': { # root logger，捕獲所有未被特定 logger 處理的日誌
        'handlers': ['console', 'info_file', 'error_file'],
        'level': 'INFO', # root logger 的默認級別
    }
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}
