# Generated by Django 5.2.2 on 2025-06-04 20:20

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('staff_id', models.CharField(max_length=20, unique=True, verbose_name='教職員編號')),
                ('department', models.CharField(max_length=100, verbose_name='部門')),
                ('position', models.CharField(max_length=100, verbose_name='職位')),
                ('employment_date', models.DateField(verbose_name='入職日期')),
                ('is_active_staff', models.BooleanField(default=True, verbose_name='是否在職')),
                ('chinese_name', models.CharField(max_length=100, verbose_name='中文姓名')),
                ('english_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='英文姓名')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女'), ('other', '其他')], max_length=10, verbose_name='性別')),
                ('date_of_birth', models.DateField(verbose_name='出生日期')),
                ('place_of_birth', models.CharField(blank=True, max_length=100, null=True, verbose_name='出生地點')),
                ('nationality', models.CharField(max_length=50, verbose_name='國籍')),
                ('hkid_passport_number', models.CharField(max_length=20, unique=True, verbose_name='身份證/護照號碼')),
                ('contact_number', models.CharField(max_length=20, verbose_name='聯絡電話')),
                ('emergency_contact_name', models.CharField(max_length=100, verbose_name='緊急聯絡人姓名')),
                ('emergency_contact_number', models.CharField(max_length=20, verbose_name='緊急聯絡人電話')),
                ('current_address', models.CharField(max_length=255, verbose_name='現居地址')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='電子郵件')),
                ('marital_status', models.CharField(blank=True, choices=[('single', '未婚'), ('married', '已婚'), ('divorced', '離婚'), ('widowed', '喪偶')], max_length=20, null=True, verbose_name='婚姻狀況')),
                ('religion', models.CharField(blank=True, max_length=50, null=True, verbose_name='宗教')),
                ('dietary_restrictions', models.CharField(blank=True, max_length=255, null=True, verbose_name='飲食限制')),
                ('health_conditions', models.TextField(blank=True, null=True, verbose_name='健康狀況')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='users_groups', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='users_user_permissions', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用戶',
                'verbose_name_plural': '用戶',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
