# Generated by Django 5.2.2 on 2025-06-05 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='chinese_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='current_address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='user',
            name='department',
        ),
        migrations.RemoveField(
            model_name='user',
            name='dietary_restrictions',
        ),
        migrations.RemoveField(
            model_name='user',
            name='emergency_contact_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='employment_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='english_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='health_conditions',
        ),
        migrations.RemoveField(
            model_name='user',
            name='hkid_passport_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_active_staff',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='user',
            name='place_of_birth',
        ),
        migrations.RemoveField(
            model_name='user',
            name='position',
        ),
        migrations.RemoveField(
            model_name='user',
            name='religion',
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='住址'),
        ),
        migrations.AddField(
            model_name='user',
            name='adjusted_salary_points',
            field=models.IntegerField(blank=True, null=True, verbose_name='調整增薪點數'),
        ),
        migrations.AddField(
            model_name='user',
            name='alumni_class',
            field=models.CharField(blank=True, max_length=100, verbose_name='級社(校友適用)'),
        ),
        migrations.AddField(
            model_name='user',
            name='alumni_class_duration',
            field=models.CharField(blank=True, max_length=50, verbose_name='級社_年數(校友適用)'),
        ),
        migrations.AddField(
            model_name='user',
            name='alumni_class_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='級社_年級(校友適用)'),
        ),
        migrations.AddField(
            model_name='user',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='大豐銀行澳門幣戶口賬號'),
        ),
        migrations.AddField(
            model_name='user',
            name='basic_salary_points',
            field=models.IntegerField(blank=True, null=True, verbose_name='薪級基本點數'),
        ),
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='出生日期'),
        ),
        migrations.AddField(
            model_name='user',
            name='birth_place',
            field=models.CharField(blank=True, max_length=100, verbose_name='出生地點'),
        ),
        migrations.AddField(
            model_name='user',
            name='departure_date',
            field=models.DateField(blank=True, null=True, verbose_name='離職日期'),
        ),
        migrations.AddField(
            model_name='user',
            name='dsej_registration_rank',
            field=models.CharField(blank=True, max_length=50, verbose_name='教青局登記職級'),
        ),
        migrations.AddField(
            model_name='user',
            name='dsej_registration_status',
            field=models.CharField(blank=True, max_length=50, verbose_name='教青局登記資料'),
        ),
        migrations.AddField(
            model_name='user',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='緊急聯絡人電話'),
        ),
        migrations.AddField(
            model_name='user',
            name='emergency_contact_relationship',
            field=models.CharField(blank=True, max_length=50, verbose_name='與緊急聯絡人之關係'),
        ),
        migrations.AddField(
            model_name='user',
            name='employment_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='受聘形式'),
        ),
        migrations.AddField(
            model_name='user',
            name='employment_type_remark',
            field=models.CharField(blank=True, max_length=255, verbose_name='受聘形式備註'),
        ),
        migrations.AddField(
            model_name='user',
            name='entry_date',
            field=models.DateField(blank=True, null=True, verbose_name='入職日期'),
        ),
        migrations.AddField(
            model_name='user',
            name='home_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='住宅電話'),
        ),
        migrations.AddField(
            model_name='user',
            name='id_expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='證件有效期'),
        ),
        migrations.AddField(
            model_name='user',
            name='id_number',
            field=models.CharField(default='', max_length=50, unique=True, verbose_name='證件號碼'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='id_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='證件類別'),
        ),
        migrations.AddField(
            model_name='user',
            name='mobile_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='手提電話'),
        ),
        migrations.AddField(
            model_name='user',
            name='name_chinese',
            field=models.CharField(blank=True, max_length=100, verbose_name='員工姓名(中文)'),
        ),
        migrations.AddField(
            model_name='user',
            name='name_foreign',
            field=models.CharField(default='', max_length=100, verbose_name='員工姓名(外文)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='origin',
            field=models.CharField(blank=True, max_length=100, verbose_name='籍貫'),
        ),
        migrations.AddField(
            model_name='user',
            name='position_grade',
            field=models.CharField(blank=True, max_length=50, verbose_name='職稱/任教年級'),
        ),
        migrations.AddField(
            model_name='user',
            name='provident_fund_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='公積金類別'),
        ),
        migrations.AddField(
            model_name='user',
            name='remark',
            field=models.TextField(blank=True, verbose_name='備註'),
        ),
        migrations.AddField(
            model_name='user',
            name='retirement_date',
            field=models.DateField(blank=True, null=True, verbose_name='退休日期'),
        ),
        migrations.AddField(
            model_name='user',
            name='social_security_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='社保號碼'),
        ),
        migrations.AddField(
            model_name='user',
            name='staff_name',
            field=models.CharField(default='', max_length=100, verbose_name='員工姓名'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='teacher_certificate_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='教師證號碼'),
        ),
        migrations.AddField(
            model_name='user',
            name='teaching_staff_rank',
            field=models.CharField(blank=True, max_length=50, verbose_name='教學人員職級'),
        ),
        migrations.AddField(
            model_name='user',
            name='teaching_staff_rank_effective_date',
            field=models.DateField(blank=True, null=True, verbose_name='教學人員職級生效日期'),
        ),
        migrations.AddField(
            model_name='user',
            name='teaching_staff_salary_grade',
            field=models.CharField(blank=True, max_length=50, verbose_name='教學人員薪級'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='電郵'),
        ),
        migrations.AlterField(
            model_name='user',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='緊急聯絡人姓名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, max_length=10, verbose_name='性別M/F'),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set_for_users_app', related_query_name='user_for_users_app', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='marital_status',
            field=models.CharField(blank=True, max_length=20, verbose_name='婚姻狀況'),
        ),
        migrations.AlterField(
            model_name='user',
            name='staff_id',
            field=models.CharField(max_length=20, unique=True, verbose_name='員工編號'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set_for_users_app', related_query_name='user_for_users_app', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.CreateModel(
            name='EducationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years', models.CharField(blank=True, max_length=50, verbose_name='就讀年份')),
                ('school', models.CharField(max_length=255, verbose_name='就讀學校')),
                ('education_level', models.CharField(max_length=100, verbose_name='教育程度')),
                ('major', models.CharField(blank=True, max_length=255, verbose_name='專科學位名稱')),
                ('certificate_date', models.DateField(blank=True, null=True, verbose_name='獲得證書日期')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_history', to='users.user', verbose_name='員工編號')),
            ],
            options={
                'verbose_name': '學歷狀況',
                'verbose_name_plural': '學歷狀況',
            },
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('relationship', models.CharField(max_length=50, verbose_name='關係')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='出生日期')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='年齡')),
                ('education_level', models.CharField(blank=True, max_length=100, verbose_name='學歷程度')),
                ('institution', models.CharField(blank=True, max_length=255, verbose_name='教育機構/任職機構')),
                ('alumni_class', models.CharField(blank=True, max_length=100, verbose_name='級社(校友適用)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to='users.user', verbose_name='員工編號')),
            ],
            options={
                'verbose_name': '家庭成員',
                'verbose_name_plural': '家庭成員',
            },
        ),
        migrations.CreateModel(
            name='ProfessionalQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='專業資格名稱')),
                ('issuing_organization', models.CharField(blank=True, max_length=255, verbose_name='頒發機構')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='頒授日期')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professional_qualifications', to='users.user', verbose_name='員工編號')),
            ],
            options={
                'verbose_name': '專業資格',
                'verbose_name_plural': '專業資格',
            },
        ),
        migrations.CreateModel(
            name='SocialActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=255, verbose_name='社團名稱')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='職位')),
                ('start_year', models.IntegerField(blank=True, null=True, verbose_name='開始年期')),
                ('end_year', models.IntegerField(blank=True, null=True, verbose_name='結束年期')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_activities', to='users.user', verbose_name='員工編號')),
            ],
            options={
                'verbose_name': '社團職務',
                'verbose_name_plural': '社團職務',
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years', models.CharField(blank=True, max_length=50, verbose_name='任職年份')),
                ('company', models.CharField(max_length=255, verbose_name='任職機構')),
                ('position', models.CharField(max_length=100, verbose_name='任職職位')),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='薪金')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experience', to='users.user', verbose_name='員工編號')),
            ],
            options={
                'verbose_name': '工作經驗',
                'verbose_name_plural': '工作經驗',
            },
        ),
    ]
