# Generated by Django 5.2.2 on 2025-06-05 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_remove_user_chinese_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '教師職員', 'verbose_name_plural': '教師職員'},
        ),
    ]
