# Generated by Django 5.2.2 on 2025-06-05 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='seniority_calculation_effective',
            field=models.BooleanField(default=True, verbose_name='年資計算有效'),
        ),
        migrations.AlterField(
            model_name='user',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('full_time_teacher', '全職教學人員(教師證)'), ('part_time_teacher', '兼職教學人員(教師證)'), ('full_time_staff', '全職職員(職員證)'), ('part_time_staff', '兼職職員(職員證)'), ('part_time_staff_no_id', '兼職職員'), ('full_time_janitor', '全職校工(職員證)'), ('part_time_janitor', '兼職校工'), ('intern_staff', '兼職實習生(職員證)'), ('short_term_intern', '短期實習生'), ('substitute_teacher', '代課老師'), ('partner_company', '合作單位(請註明公司名)'), ('leisure_activity_tutor', '正課餘暇導師'), ('co_curricular_teacher', '聯課活動導師'), ('volunteer_co_curricular', '義務聯課活動導師'), ('part_time_librarian', '圖書館兼職人員')], max_length=50, verbose_name='受聘形式'),
        ),
    ]
