# Generated by Django 5.2.2 on 2025-06-05 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_seniority_calculation_effective_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmploymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='開始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='結束日期')),
                ('department', models.CharField(max_length=100, verbose_name='部門')),
                ('position', models.CharField(max_length=100, verbose_name='職位')),
                ('employment_type', models.CharField(choices=[('full_time_teacher', '全職教學人員(教師證)'), ('part_time_teacher', '兼職教學人員(教師證)'), ('full_time_staff', '全職職員(職員證)'), ('part_time_staff', '兼職職員(職員證)'), ('part_time_staff_no_id', '兼職職員'), ('full_time_janitor', '全職校工(職員證)'), ('part_time_janitor', '兼職校工'), ('intern_staff', '兼職實習生(職員證)'), ('short_term_intern', '短期實習生'), ('substitute_teacher', '代課老師'), ('partner_company', '合作單位(請註明公司名)'), ('leisure_activity_tutor', '正課餘暇導師'), ('co_curricular_teacher', '聯課活動導師'), ('volunteer_co_curricular', '義務聯課活動導師'), ('part_time_librarian', '圖書館兼職人員')], max_length=50)),
                ('remark', models.TextField(blank=True, verbose_name='備註')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employment_records', to='users.user')),
            ],
            options={
                'verbose_name': '在職記錄',
                'verbose_name_plural': '在職記錄',
            },
        ),
    ]
