# Generated by Django 5.2.2 on 2025-06-05 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_employmentrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('id_number', models.CharField(max_length=50)),
                ('mobile_phone', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('pending', '待審核'), ('approved', '已批准'), ('rejected', '已拒絕')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '求職申請',
                'verbose_name_plural': '求職申請',
            },
        ),
    ]
