# Generated by Django 5.2.2 on 2025-06-05 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_jobapplication'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobapplication',
            options={'verbose_name': '入職申請', 'verbose_name_plural': '入職申請'},
        ),
    ]
