# Generated by Django 5.2.2 on 2025-06-05 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_jobapplication_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='applied_position',
            field=models.CharField(default='', max_length=100, verbose_name='申請職位'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='創建時間'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='id_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='身份證號'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='mobile_phone',
            field=models.CharField(max_length=20, verbose_name='手機號碼'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='name',
            field=models.CharField(max_length=100, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('pending', '待審核'), ('approved', '已批准'), ('rejected', '已拒絕')], default='pending', max_length=20, verbose_name='狀態'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新時間'),
        ),
    ]
