# Generated by Django 5.2.2 on 2025-06-05 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_jobapplication_applied_position_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('id_number', models.CharField(max_length=50, unique=True, verbose_name='身份證號')),
                ('mobile_phone', models.CharField(max_length=20, verbose_name='手機號碼')),
                ('department', models.CharField(max_length=100, verbose_name='部門')),
                ('position', models.CharField(max_length=100, verbose_name='職位')),
                ('proposed_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='建議薪資')),
                ('proposed_start_date', models.DateField(verbose_name='建議入職日期')),
                ('status', models.CharField(choices=[('pending', '待審核'), ('approved', '已批准'), ('rejected', '已拒絕')], default='pending', max_length=20, verbose_name='狀態')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '入職申請',
                'verbose_name_plural': '入職申請',
            },
        ),
        migrations.DeleteModel(
            name='JobApplication',
        ),
    ]
