# Generated by Django 5.2.2 on 2025-06-05 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_onboardingapplication_delete_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='employmentrecord',
            name='count_for_seniority',
            field=models.BooleanField(default=True, verbose_name='計入年資'),
        ),
        migrations.AddField(
            model_name='user',
            name='seniority',
            field=models.IntegerField(default=0, verbose_name='在職年資'),
        ),
    ]
