# Generated by Django 5.2.2 on 2025-06-05 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_employmentrecord_count_for_seniority_user_seniority'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, max_length=100, verbose_name='職稱'),
        ),
        migrations.AddField(
            model_name='user',
            name='teaching_grade',
            field=models.CharField(blank=True, max_length=100, verbose_name='任教年級'),
        ),
    ]
