# Generated by Django 5.2.2 on 2025-06-05 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_position_user_teaching_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='職稱'),
        ),
        migrations.AlterField(
            model_name='user',
            name='teaching_grade',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='任教年級'),
        ),
    ]
