# Generated by Django 5.2.2 on 2025-06-05 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_user_position_alter_user_teaching_grade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employmentrecord',
            old_name='count_for_seniority',
            new_name='is_effective_for_seniority',
        ),
        migrations.AlterField(
            model_name='user',
            name='seniority',
            field=models.FloatField(default=0.0, verbose_name='Seniority (Years)'),
        ),
    ]
