# Generated by Django 5.2.2 on 2025-06-05 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_rename_count_for_seniority_employmentrecord_is_effective_for_seniority_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employmentrecord',
            old_name='is_effective_for_seniority',
            new_name='count_for_seniority',
        ),
        migrations.AlterField(
            model_name='user',
            name='seniority',
            field=models.IntegerField(default=0, verbose_name='在職年資'),
        ),
    ]
