# Generated by Django 5.2.2 on 2025-06-10 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_rename_is_effective_for_seniority_employmentrecord_count_for_seniority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationhistory',
            name='is_overseas_study',
            field=models.BooleanField(default=False, verbose_name='是否留學經歷'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_macao_pr',
            field=models.BooleanField(default=True, verbose_name='澳門永久性居民'),
        ),
        migrations.AlterField(
            model_name='employmentrecord',
            name='employment_type',
            field=models.CharField(choices=[('full_time_teacher', '全職教學人員(教師證)'), ('part_time_teacher', '兼職教學人員(教師證)'), ('full_time_staff', '全職職員(職員證)'), ('part_time_staff', '兼職職員(職員證)'), ('part_time_staff_no_id', '兼職職員'), ('full_time_janitor', '全職校工(職員證)'), ('part_time_janitor', '兼職校工'), ('intern_staff', '兼職實習生(職員證)'), ('short_term_intern', '短期實習生'), ('substitute_teacher', '代課老師'), ('partner_company', '合作單位(請註明公司名)'), ('leisure_activity_tutor', '正課餘暇導師'), ('co_curricular_teacher', '聯課活動導師'), ('volunteer_co_curricular', '義務聯課活動導師'), ('part_time_librarian', '圖書館兼職人員')], max_length=50, verbose_name='受聘形式'),
        ),
        migrations.AlterField(
            model_name='employmentrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employment_records', to='users.user', verbose_name='員工編號'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, max_length=10, verbose_name='性別'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id_type',
            field=models.CharField(blank=True, choices=[('macao_id', '澳門居民身份證'), ('passport', '護照'), ('other', '其他')], max_length=50, verbose_name='證件類別'),
        ),
    ]
