# Generated by Django 5.2.2 on 2025-06-12 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_submission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationeducation',
            name='is_foreign_national',
            field=models.BooleanField(default=False, verbose_name='是否為外籍人士'),
        ),
        migrations.AddField(
            model_name='applicationeducation',
            name='is_overseas_study',
            field=models.BooleanField(default=False, verbose_name='是否留學'),
        ),
    ]
