# Generated by Django 5.2.2 on 2025-06-12 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_submission', '0002_applicationeducation_is_foreign_national_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationeducation',
            name='is_foreign_national',
        ),
        migrations.AddField(
            model_name='applicationeducation',
            name='is_phd',
            field=models.BooleanField(default=False, verbose_name='是否博士學位(PhD)'),
        ),
        migrations.AddField(
            model_name='staffapplication',
            name='is_foreign_national',
            field=models.BooleanField(default=False, verbose_name='是否外籍人士'),
        ),
        migrations.AlterField(
            model_name='applicationeducation',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='application_submission.staffapplication', verbose_name='所屬申請'),
        ),
        migrations.AlterField(
            model_name='applicationeducation',
            name='certificate_date',
            field=models.DateField(blank=True, null=True, verbose_name='獲授證書日期'),
        ),
        migrations.AlterField(
            model_name='applicationeducation',
            name='degree_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='專科/學位名稱'),
        ),
        migrations.AlterField(
            model_name='applicationeducation',
            name='education_level',
            field=models.CharField(max_length=100, verbose_name='學歷程度'),
        ),
        migrations.AlterField(
            model_name='applicationeducation',
            name='school_name',
            field=models.CharField(max_length=200, verbose_name='就讀學校'),
        ),
        migrations.AlterField(
            model_name='applicationeducation',
            name='study_period',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='就讀年份(起-止)'),
        ),
    ]
