# Generated by Django 5.2.2 on 2025-08-12 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_submission', '0003_remove_applicationeducation_is_foreign_national_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationeducation',
            name='is_master',
            field=models.BooleanField(default=False, verbose_name='是否碩士學位(Master)'),
        ),
    ]
