# Generated by Django 5.2.2 on 2025-08-16 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_submission', '0004_applicationeducation_is_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffapplication',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='application_photos/', verbose_name='個人相片'),
        ),
    ]
