# Generated by Django 5.2.2 on 2025-08-16 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_submission', '0005_staffapplication_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffapplication',
            name='is_master',
            field=models.BooleanField(default=False, verbose_name='是否碩士學位'),
        ),
        migrations.AddField(
            model_name='staffapplication',
            name='is_overseas_study',
            field=models.BooleanField(default=False, verbose_name='是否留學'),
        ),
        migrations.AddField(
            model_name='staffapplication',
            name='is_phd',
            field=models.BooleanField(default=False, verbose_name='是否博士學位'),
        ),
    ]
