# Generated by Django 5.2.2 on 2025-08-18 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application_submission', '0006_staffapplication_is_master_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffapplication',
            name='is_foreign_national',
        ),
        migrations.RemoveField(
            model_name='staffapplication',
            name='is_master',
        ),
        migrations.RemoveField(
            model_name='staffapplication',
            name='is_overseas_study',
        ),
        migrations.RemoveField(
            model_name='staffapplication',
            name='is_phd',
        ),
    ]
