# Generated by Django 5.2.2 on 2025-11-12 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_submission', '0007_remove_staffapplication_is_foreign_national_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffapplication',
            name='is_foreign_national',
            field=models.BooleanField(default=False, verbose_name='是否外籍人士'),
        ),
        migrations.AddField(
            model_name='staffapplication',
            name='is_master',
            field=models.BooleanField(default=False, verbose_name='是否碩士學位'),
        ),
        migrations.AddField(
            model_name='staffapplication',
            name='is_overseas_study',
            field=models.BooleanField(default=False, verbose_name='是否留學'),
        ),
        migrations.AddField(
            model_name='staffapplication',
            name='is_phd',
            field=models.BooleanField(default=False, verbose_name='是否博士學位'),
        ),
    ]
